### ISSUE TITLE
buster command not working

### ISSUE THREAD

**Issue by myKingEdem** [axitkhurana/buster#9]
pip install buster
Requirement already satisfied (use --upgrade to upgrade): buster in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): async==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): gitdb==0.5.4 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): smmap==0.8.2 in /usr/local/lib/python2.7/site-packages (from buster)
Cleaning up...
bash-4.2$ buster --version
bash: buster: command not found

**Comment by axitkhurana** [comment]
Looks `/usr/local/bin` is not present in your PATH. To confirm installation of buster, you can check the folder `/usr/local/lib/python2.7/site-packages` for a `buster` directory.

If `/usr/local/bin` directory has a file named `buster`, then try the following:

```
export PATH="$PATH:/usr/local/bin"
buster --version
```

(You should add the export line to your .bashrc file to avoid doing that every time you open a new terminal)

If this doesn't work, you can download the buster.py file, mark it executable and use that. You can use the following commands to do that:

```
wget https://raw.github.com/axitkhurana/buster/master/buster/buster.py
chmod u+x buster.py
./buster.py --version
```

Hope this helps, let me know if you face any issues.

**Comment by myKingEdem** [comment]
@axitkhurana I have a `buster` directory in `/usr/local/lib/python2.7/site-packages`, but not in `/usr/local/bin`. I think the script should be changed so that it automatically adds a file under the bin directory. I say this because I have files such as git, heroku, npm, ack, wget, rbenv in the bin directory, while I have mostly folders under the lib directory. I don't know the relationship, but it makes sense intuitively in that the single files under the bin directory make those commands work. I have an export line to node_modules; besides that almost all commands work without an explicit export in bashrc.

Or, what export line can I add to to .bashrc to make it work. I've already tried `/usr/local/lib`, `PATH:/usr/local/lib`,  and `/usr/local/lib/python2.7/site-packages/buster` and restarted the console after each time, but no cigar.

**Comment by axitkhurana** [comment]
@rkcudjoe Thanks for trying these out. `pip` handles creation of file in the bin directory, so modifying the script won't help, the issue is with the pip version or installation.

May I suggest using [virtualenv](http://docs.python-guide.org/en/latest/starting/install/osx/#virtualenv) _or_ using `sudo pip install buster` to install buster for all users?

If nothing helps 

```
wget https://raw.github.com/axitkhurana/buster/master/buster/buster.py
chmod u+x buster.py
./buster.py --version
```

should definitely work as buster.py can work without installation. You need wget as mentioned in the README which you can install using `brew install wget`.

**Comment by myKingEdem** [comment]
@axitkhurana so which version of python should I install. I use homebrew, so I guess it installs the latests version. What are the recommended versions of python and pip? I already have wget installed, but I would rather not use it. And I don't do a lot of python programming so I would like to avoid virtualenv. installations should be easy through pip and homebrew.

**Comment by axitkhurana** [comment]
Python 2.7+ should be good, homebrew's version should be the latest. I'm using pip version 1.4.1.

Any particular reason you don't want to use wget?

Also, can you please reinstall buster and paste the terminal output here? Would be very helpful in debugging.
You can do that by calling `pip uninstall buster;pip install buster`.

Thanks!

**Comment by weisserj** [comment]
Following up (5 months later) because I've followed this and encountered the same errors

Here's the terminal output...
pip uninstall buster;pip install buster
Uninstalling buster:
  /usr/local/lib/python2.7/site-packages/buster-0.1.2-py2.7.egg-info
  /usr/local/lib/python2.7/site-packages/buster/**init**.py
  /usr/local/lib/python2.7/site-packages/buster/**init**.pyc
  /usr/local/lib/python2.7/site-packages/buster/_version.py
  /usr/local/lib/python2.7/site-packages/buster/_version.pyc
  /usr/local/lib/python2.7/site-packages/buster/buster.py
  /usr/local/lib/python2.7/site-packages/buster/buster.pyc
  /usr/local/share/python/buster
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/commands/uninstall.py", line 41, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/req.py", line 888, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/req.py", line 495, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/req.py", line 1492, in remove
    renames(path, new_path)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg/pip/util.py", line 273, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 297, in move
    rmtree(src)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 248, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/buster-0.1.2-py2.7.egg-info/dependency_links.txt'

Storing complete log in /Users/weisserj/.pip/pip.log
Requirement already satisfied (use --upgrade to upgrade): buster in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): async==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): gitdb==0.5.4 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): smmap==0.8.2 in /usr/local/lib/python2.7/site-packages (from buster)
Cleaning up...

Then when I type "buster --version"...
-bash: buster: command not found

**Comment by axitkhurana** [comment]
@weisserj Looks like you don't have permissions to write to `/usr/local/lib/` . Using `sudo` or changing the permissions should fix this.

See http://stackoverflow.com/questions/4359870/unable-to-install-pip-permission-denied-error

**Comment by weisserj** [comment]
Thanks for the quick reply...now I'm not seemingly having an issue uninstalling/reinstalling but still getting command not found.

bash-3.2# pip uninstall buster;pip install buster
Uninstalling buster:
  /usr/local/lib/python2.7/site-packages/buster-0.1.2-py2.7.egg-info
  /usr/local/lib/python2.7/site-packages/buster/**init**.py
  /usr/local/lib/python2.7/site-packages/buster/**init**.pyc
  /usr/local/lib/python2.7/site-packages/buster/_version.py
  /usr/local/lib/python2.7/site-packages/buster/_version.pyc
  /usr/local/lib/python2.7/site-packages/buster/buster.py
  /usr/local/lib/python2.7/site-packages/buster/buster.pyc
  /usr/local/share/python/buster
Proceed (y/n)? y
  Successfully uninstalled buster
Downloading/unpacking buster
  Downloading buster-0.1.2.tar.gz
  Running setup.py egg_info for package buster

Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): async==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): gitdb==0.5.4 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): smmap==0.8.2 in /usr/local/lib/python2.7/site-packages (from buster)
Installing collected packages: buster
  Running setup.py install for buster

```
Installing buster script to /usr/local/share/python
```

Successfully installed buster
Cleaning up...
bash-3.2# buster --version
bash: buster: command not found

**Comment by axitkhurana** [comment]
Please add `/usr/local/share/python` to your PATH.

```
export PATH=$PATH:/usr/local/share/python
buster --version
```

Add the export line to your .bashrc or .profile file to permanently add it to your path.

**Comment by ghost** [comment]
Okay I tried this over the weekend and seem to be getting the same issues after entering buster setup and plugging in my git repo. 

Terminal print:

```
Traceback (most recent call last):
File "/usr/local/bin/buster", line 9, in <module> load_entry_point('buster==0.1.2', 'console_scripts', 'buster')()
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buster/buster.py", line 90, in main
repo = Repo.init(static_path)
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/git/repo/base.py", line 656, in init
output = git.init(**kwargs)
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/git/cmd.py", line 227, in <lambda>
return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/git/cmd.py", line 456, in _call_process
return self.execute(call, **_kwargs)
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/git/cmd.py", line 335, in execute
**subprocess_kwargs
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
errread, errwrite)
File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

Weirdly enough the export path command doesn't work, although I'm not used to git so I might be doing something wrong.

**Comment by ghost** [comment]
Ok so after a bit of a faff and a lot of messing around I managed to fix the issues above. 

*bare in mind that this is OSX and that before trying the things below you should add "/usr/local/share/python", the best way for me was to open the file in a text editor and add the line

## Mac Steps:
- First thing's first: don't install node through a package, install it through homebrew
- Second: install git through homebrew
- Third: install docopt through homebrew, make sure to keep running "brew update" and "brew doctor" to guarantee that there are no errors
- Forth: make sure that buster is uninstalled through pip
- Fifth: go to    "/usr/local/bin/"    and    "usr/local/lib/python2.7/site-packages"    and "ls" to see files, look out for buster and delete each file manually using "rm" 
- Six: Reinstall buster and you'll notice that there are no more issues

**Comment by stobasan** [comment]
I have already installed:

pip -V
pip 1.5.6 from C:\Python34\lib\site-packages (python 3.4)

But I get a following error when trying to install buster on windows 7:

pip install buster
Downloading/unpacking buster
  Downloading buster-0.1.2.tar.gz
  Running setup.py (path:C:\Users\oem\AppData\Local\Temp\pip_build_oem\buster\setup.py) egg_info for package buster

Downloading/unpacking GitPython==0.3.2.RC1 (from buster)
  Running setup.py (path:C:\Users\oem\AppData\Local\Temp\pip_build_oem\GitPython\setup.py) egg_info for package GitPython

```
warning: no files found matching 'README'
```

Downloading/unpacking async==0.6.1 (from buster)
  Downloading async-0.6.1.tar.gz
  Running setup.py (path:C:\Users\oem\AppData\Local\Temp\pip_build_oem\async\setup.py) egg_info for package async
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\oem\AppData\Local\Temp\pip_build_oem\async\setup.py", line 24
        print "Ignored failure when building extensions, pure python modules will be used instead"
                                                                                                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\oem\AppData\Local\Temp\pip_build_oem\async\setup.py", line 24

```
print "Ignored failure when building extensions, pure python modules will be used instead"
```

SyntaxError: invalid syntax

**Comment by stobasan** [comment]
Downgrading Python to version 2.7.x fixed the problem and allowed for installing Buster with pip.

**Comment by jmtan** [comment]
Hi all,

I've followed the steps, yet I am still having the same error. Please help

$ pip install buster
Collecting buster
  Using cached buster-0.1.3.tar.gz
Collecting GitPython==0.3.2.RC1 (from buster)
  Using cached GitPython-0.3.2.RC1.tar.gz
    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/setuptools/dist.py:292: UserWarning: The version specified ('0.3.2 RC1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
Collecting async==0.6.1 (from buster)
  Using cached async-0.6.1.tar.gz
Collecting docopt==0.6.1 (from buster)
  Using cached docopt-0.6.1.tar.gz
Collecting gitdb==0.5.4 (from buster)
  Using cached gitdb-0.5.4.tar.gz
Collecting pyquery==1.2.8 (from buster)
  Using cached pyquery-1.2.8.zip
Collecting smmap==0.8.2 (from buster)
  Using cached smmap-0.8.2.tar.gz
Collecting lxml>=2.1 (from pyquery==1.2.8->buster)
  Using cached lxml-3.4.1.tar.gz
    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
Requirement already satisfied (use --upgrade to upgrade): cssselect in /usr/local/lib/python2.7/site-packages (from pyquery==1.2.8->buster)
Installing collected packages: lxml, smmap, pyquery, gitdb, docopt, async, GitPython, buster
  Running setup.py install for lxml
    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    building 'lxml.etree' extension
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -I/private/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/src/lxml/includes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.10-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    In file included from src/lxml/lxml.etree.c:239:
    /private/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-Fz23mJ-record/install-record.txt --single-version-externally-managed --compile:
    /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'

```
  warnings.warn(msg)

Building lxml version 3.4.1.

Building without Cython.

Using build configuration of libxslt 1.1.28

running install

running build

running build_py

creating build

creating build/lib.macosx-10.10-x86_64-2.7

creating build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/_elementpath.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/builder.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/cssselect.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/doctestcompare.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/ElementInclude.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/sax.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/usedoctest.py -> build/lib.macosx-10.10-x86_64-2.7/lxml

creating build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

creating build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/builder.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/clean.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/defs.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/diff.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/formfill.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/html5parser.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/soupparser.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/html

creating build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron

copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron

copying src/lxml/lxml.etree.h -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.10-x86_64-2.7/lxml

copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/config.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.10-x86_64-2.7/lxml/includes

creating build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources

creating build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/rng

copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/rng

creating build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl

creating build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.10-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

creating build/temp.macosx-10.10-x86_64-2.7

creating build/temp.macosx-10.10-x86_64-2.7/src

creating build/temp.macosx-10.10-x86_64-2.7/src/lxml

clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -I/private/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/src/lxml/includes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.10-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace

In file included from src/lxml/lxml.etree.c:239:

/private/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found

#include "libxml/xmlversion.h"

         ^

1 error generated.

error: command 'clang' failed with exit status 1

----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-Fz23mJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/x9/5z2bwmss7z19whl0v8pdrxpc0000gn/T/pip-build-kj5e3z/lxml
```

**Comment by silverfangs** [comment]
@jmtan , same issue as #60 

You can probably solved it by install the command line tool for xcode:
Try `xcode-select --install`
